// vocab.js
const vocabList = [
    { de: "Beweis, Bestätigung", ar: "إثبات" },
    { de: "Vater", ar: "أب" },
    { de: "mein Vater", ar: "أبي" },
    { de: "Bruder", ar: "أخ" },
    { de: "Schwester", ar: "أخت" },
    { de: "Tür", ar: "باب(Plural = أبواب)" },
    { de: "Krone", ar: "تاج" },
    { de: "und", ar: "و" },
    { de: "Bruder und Schwester", ar: "أخ وأخت" },
    { de: "Suche, Forschungsarbeit", ar: "بحث، أبحاث" },
    { de: "oder", ar: "أو" },
    { de: "ich suche", ar: "أبحث" },
    { de: "Oh (Anredepartikel)", ar: "يا" },
    { de: "unter", ar: "تحت" },
    { de: "Oh Bruder!", ar: "يا أخ!" },
    { de: "Schleier", ar: "حجاب" },
    { de: "welche(r/s)?", ar: "أي؟" },
    { de: "Pilgerfahrt", ar: "حج" },
    { de: "Geliebter", ar: "حبيب" },
    { de: "Pilger", ar: "حاج ج حجاج" },
    { de: "mein Liebling", ar: "حبيبي" },
    { de: "Liebe", ar: "حب" },
    { de: "ich liebe, ich mag", ar: "أحب" },
    { de: "Haus", ar: "بيت ج بيوت" },
    { de: "Möbel, Mobiliar", ar: "أثاث" },
    { de: "Kopf", ar: "رأس" },
    { de: "Lektion", ar: "درس ج دروس" },
    { de: "Meer", ar: "بحر" },
    { de: "studieren, lernen", ar: "درس، يدرس" },
    { de: "trinken", ar: "شرب، يشرب" },
    { de: "Löwe", ar: "أسد" },
    { de: "Tee", ar: "شاي" },
    { de: "frei", ar: "حرّ" },
    { de: "Morgen", ar: "صباح" },
    { de: "wenn, falls", ar: "إذا" },
    { de: "Freund, Besitzer", ar: "صاحب ج أصحاب" },
    { de: "Haus (fem.)", ar: "دار ج دور" },
    { de: "Person", ar: "شخص ج أشخاص" },
    { de: "hinausgehen", ar: "خرج" },
    { de: "Erde (fem.)", ar: "أرض" },
    { de: "Nimm!", ar: "خذ!" },
    { de: "Bäume (Koll.)", ar: "شجر" },
    { de: "Nachricht", ar: "خبر ج أخبار" },
    { de: "grün", ar: "أخضر" },
    { de: "Brot", ar: "خبز" },
    { de: "Streik", ar: "إضراب" },
    { de: "grüner Salat", ar: "خس" },
    { de: "Minister", ar: "وزير ج وزراء" },
    { de: "Stop! Halt an!", ar: "قف!" },
    { de: "Medizin", ar: "طب" },
    { de: "wissen, kennen, erfahren", ar: "عرف" },
    { de: "Arzt", ar: "طبيب" },
    { de: "Wirtschaft", ar: "إقتصاد" },
    { de: "Linie, Schrift", ar: "خط ج خطوط" },
    { de: "Äpfel (Koll.)", ar: "تفاح" },
    { de: "Kartoffeln (Koll.)", ar: "بطاطا" },
    { de: "Osten, Orient", ar: "شرق" },
    { de: "Glück, Los", ar: "حظ" },
    { de: "Westen", ar: "غرب" },
    { de: "öffnen", ar: "فتح" },
    { de: "arabisch, Araber", ar: "عربي ج عرب" },
    { de: "Wetter", ar: "طقس" },
    { de: "schneiden, überqueren", ar: "قطع" },
    { de: "verkaufen", ar: "باع" },
    { de: "Küste, Ufer", ar: "شط" },
    { de: "nach (zeitl.)", ar: "بعد" },
    { de: "Recht (Pl. auch: Jura)", ar: "حق ج حقوق" },
    { de: "reisen", ar: "سافر، يسافر" },
    { de: "so, dann, denn, und", ar: "ف" },
    { de: "in", ar: "في" },
    { de: "Bagdad", ar: "بغداد" },
    { "de": "Wasser", "ar": "مِياه" },
  { "de": "Buch", "ar": "كِتاب ج كُتُب" },
  { "de": "wichtig", "ar": "مُهَمّ" },
  { "de": "König", "ar": "مَلِك ج مُلوك" },
  { "de": "wohnen", "ar": "سَكَنَ، يَسْكُنُ" },
  { "de": "Arbeit, Werk", "ar": "عَمَل ج أَعْمال" },
  { "de": "bei", "ar": "عِنْدَ" },
  { "de": "sprechen", "ar": "تَكَلَّمَ" },
  { "de": "groß", "ar": "كَبِير ج كِبار" },
  { "de": "mit", "ar": "مَعَ" },
  { "de": "klein", "ar": "صَغِير ج صِغار" },
  { "de": "Student", "ar": "طالِب" },
  { "de": "Tag", "ar": "يَوْم ج أَيَّام" },
  { "de": "freundlich, nett", "ar": "لَطِيف" },
  { "de": "schön", "ar": "جَمِيل" },
  { "de": "Mensch", "ar": "إِنْسان" },
  { "de": "Mittag", "ar": "ظُهْر" },
  { "de": "Warte!", "ar": "إِنْتَظِرْ!" },
  { "de": "essen", "ar": "أَكَلَ" },
  { "de": "hier", "ar": "هُنا" },
  { "de": "viel", "ar": "كَثِير" },
  { "de": "dort, es gibt", "ar": "هُناكَ" },
  { "de": "ausländisch, Ausländer", "ar": "أَجْنَبِيّ ج أَجانِب" },
  { "de": "Gott", "ar": "الله" }
];
